name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

    

  build:

    runs-on: ubuntu-latest

    steps:
    - name: OS version
      # You may pin to the exact commit or the version.
      # uses: sersoft-gmbh/os-version-action@f9cee81334dc5f325ad0d8db036bb3de5d3e0fed
    - uses: sersoft-gmbh/os-version-action@v2.0.0
    
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag my-image-name:$(date +%s)

